name: CI/CD Deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) (Opcional) Checkout local — não é usado para copiar nada, mas você pode precisar 
      #    caso venha a rodar testes ou linters aqui antes do deploy.
      - name: Checkout do código
        uses: actions/checkout@v4

      # 2) Carrega sua chave no ssh-agent
      - name: Configurar SSH-Agent
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # 3) Conecta na VPS e faz clone/pull + docker compose
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e

            # Diretório remoto onde ficará seu app
            DEPLOY_DIR=/home/${{ secrets.VPS_USER }}/app

            # Se não existir, clona o repo
            if [ ! -d "$DEPLOY_DIR/.git" ]; then
              git clone git@github.com:SEU_USUARIO/SEU_REPO.git "$DEPLOY_DIR"
            fi

            # Vai para o diretório e garante estar na última versão
            cd "$DEPLOY_DIR"
            git fetch --all
            git reset --hard origin/main

            # (Re)constrói e sobe os containers
            docker compose up -d --build
