      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e

            DEPLOY_DIR=/home/${{ secrets.VPS_USER }}/app

            if [ -d "$DEPLOY_DIR" ]; then
              # Se existir, verificar se é git
              if [ -d "$DEPLOY_DIR/.git" ]; then
                echo "🚀 Atualizando repositório existente"
                cd "$DEPLOY_DIR"
                git fetch --all
                git reset --hard origin/main
              else
                echo "⚠️ Diretório existe mas não é Git. Removendo e clonando do zero."
                rm -rf "$DEPLOY_DIR"
                git clone git@github.com:SEU_USUARIO/SEU_REPO.git "$DEPLOY_DIR"
              fi
            else
              echo "📂 Diretório não existe. Clonando pela primeira vez."
              git clone git@github.com:SEU_USUARIO/SEU_REPO.git "$DEPLOY_DIR"
            fi

            cd "$DEPLOY_DIR"
            echo "🐳 Iniciando Docker Compose"
            docker compose up -d --build
