name: CI/CD Deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar SSH
        uses: appleboy/scp-action@v1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}    # <— aqui
          # key_path: ~/.ssh/id_ed25519          # ou, se preferir, use key_path
          script: |
            DEPLOY_DIR=/home/${{ secrets.VPS_USER }}/app
            if [ ! -d "$DEPLOY_DIR" ]; then
              git clone git@github.com:SEU_USUARIO/SEU_REPO.git $DEPLOY_DIR
            fi
            cd $DEPLOY_DIR
            git fetch --all
            git reset --hard origin/main
            docker compose up -d --build
